build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

filter:
  excluded_paths:
    - 'build/*'
    - 'vendor/*'

checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        additive: false