build:
  dependencies:
    before:
      - cp config/parameters.scrutinizer.yml config/parameters.yml
      - cp db/sql_importer.travis.sqlite db/sql_importer.sqlite
  project_setup:
    before:
      - mysql -e 'CREATE DATABASE scrutinizer'
      - psql -c 'pg_upgrade;' -U postgres
  environment:
    mysql: 5.6
    postgresql: true
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          -
            command: 'vendor/bin/phpunit --coverage-clover=build/coverage/coverage-clover-file'
            coverage:
                file: 'build/coverage/coverage-clover-file'
                format: 'clover'

filter:
  excluded_paths:
    - 'build/*'
    - 'vendor/*'

checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        additive: false