language: php

sudo: required

dist: trusty

php:
  - 7.1

addons:
  postgresql: '9.5'

services:
  - mysql
  - postgresql

global:
  - REPORT_EXIT_STATUS=1

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_script:
  - cp config/parameters.travis.yml config/parameters.yml
  - cp db/sql_importer.travis.sqlite db/sql_importer.sqlite
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - psql -c 'create database travis;' -U postgres

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

matrix:
  fast_finish: true